CREATE TABLE t_user_group (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES m_users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    group_id UUID REFERENCES m_groups(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    is_valid BOOLEAN NOT NULL DEFAULT true,
    added_at TIMESTAMPTZ NOT NULL
);
