// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (MUser, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	FindUser(ctx context.Context, id uuid.UUID) (MUser, error)
	FindUserForLogin(ctx context.Context, loginID string) (MUser, error)
	GetUsers(ctx context.Context) ([]MUser, error)
	GetUsersFromName(ctx context.Context, dollar_1 pgtype.Text) ([]MUser, error)
	UpdateUserLoggedAt(ctx context.Context, id uuid.UUID) (MUser, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (MUser, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (MUser, error)
}

var _ Querier = (*Queries)(nil)
